### ISSUE TITLE
Question: Is doWork() thread-safe?

### ISSUE THREAD

**Issue by rahmadid** [Red-Folder/bgs-core#15]
First, thank you for this great plugin :)

Question: I see that doWork() can be called from the timer (as scheduled) and be called manually (using runOnce). What if doWork() is currently running (assume a long process) then I call runOnce(), is it safe? Should I use synchronized() inside doWork()?

Thank you for your answer.

**Comment by Red-Folder** [comment]
No further activity.  Closing issue
