### ISSUE TITLE
getting error - AndroidRuntime :  Unable to instantiate service 

### ISSUE THREAD

**Issue by senthilraj** [Red-Folder/bgs-core#21]
Hi, first of all thanks for this plugin, i am the new of phonegap, i have create app via CLI and install plugin sample: using this link: https://github.com/Red-Folder/bgs-core/wiki/Using-the-MyService-Sample

after run this app, then getting this error below,

ava.lang.RuntimeException: Unable to instantiate service com.red_folder.phonegap.plugin.backgroundservice.sample.MyService: java.lang.ClassNotFoundException: Didn't find class "com.red_folder.phonegap.plugin.backgroundservice.sample.MyService" on path: DexPathList[[zip file "/data/app/com.service.app-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.service.app-1, /system/lib]]

 please help ASAP:
I am waiting for your reply, 
thanks advance

**Comment by Red-Folder** [comment]
Not sure why you are getting this.  It looks like it has compiled and built.

I'd suggest performing a clean.

Then double check that the class is only in the project once.

**Comment by Red-Folder** [comment]
@senthilraj Is this still an open issue?

**Comment by Red-Folder** [comment]
No further response - thus closing
