### ISSUE TITLE
How to apply in geolocation phonegap

### ISSUE THREAD

**Issue by v4vishnuprasad** [Red-Folder/bgs-core#22]
I am using geolocation app for getting current location by phonegap. I would like to implement it in my app so that i can get user location in definite interval of time. I need to work this even if user phone restarts(switch off and switch on).But am building the phonegap aap with adobe account (uploading the .zip and downloading the apk). Am not able to implement this background plugin in my app.(not familiar with folder structure and all). Can u please explain it with an implemented example  . 
Note : Am using linux machine for developing .
Hope you will help me. Thank you.

**Comment by Red-Folder** [comment]
I've started to build a Plugin for this.  This can be found here -> https://github.com/Red-Folder/GPS-Service-Plugin

It is work in progress and is likely to be some time before I get a chance to complete it - but it may help you.

**Comment by v4vishnuprasad** [comment]
Thank you. for helping me..

Please let me know when you finish this.

I will also  try to complete it from my side.


On Wed, Mar 11, 2015 at 9:02 PM, Mark Taylor <notifications@github.com>
wrote:

> I've started to build a Plugin for this. This can be found here ->
> https://github.com/Red-Folder/GPS-Service-Plugin
>
> It is work in progress and is likely to be some time before I get a chance
> to complete it - but it may help you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Red-Folder/bgs-core/issues/22#issuecomment-78286871>.
>



-- 

With Regards,

*Vishnu Prasad*
Software Programmer
Ti Technologies
http://www.titechnologies.in/
<http://www.titechnologies.in>
