### ISSUE TITLE
ReflectionHelper missing

### ISSUE THREAD

**Issue by xgvargas** [Red-Folder/bgs-core#24]
I can't compile due to this missing file.

**Comment by xgvargas** [comment]
It looks like the there is no target defined for it inside plugin.xml. I moved the file inside platform/android/... and it compiles now.

**Comment by Red-Folder** [comment]
@xgvargas Thanks for that.  I completely missed it.

Fixed in the commit 7a2102467e4e717318476be589407fcd23d0b4ea

**Comment by marol-hadidjaja** [comment]
After add this plugin, and run in Android Studio, I got error that this app cannot find MyService.html. How should I fix this problem?

**Comment by xgvargas** [comment]
Thank you @Red-Folder. Your plugin is working like a charm in here.
