### ISSUE TITLE
Appery Install compiler error

### ISSUE THREAD

**Issue by adavidsburg** [Red-Folder/bgs-core#25]
Hi!

This seems like an amazing plugin but I've been my head up against a wall trying to get it installed in an Appery.  I get a compiler error every time:

"/retsetere/src/com/red_folder/phonegap/plugin/backgroundservice/BackgroundServicePluginLogic.java:[710,16] error: reference to put is ambiguous, both method put(String,Collection) in JSONObject and method put(String,Map) in JSONObject match"

Maybe that I will have add everything in eclipse, but just curious if you had a quick fix?

Thanks a lot for all your hard work on this!

-Andrew

**Comment by Red-Folder** [comment]
Never used Appery,  Is it based on Cordova?

I'm afraid I can't tell you if the plugin will work with it as I'm not familiar with it

**Comment by Red-Folder** [comment]
No further activity - thus closing question
