### ISSUE TITLE
com.red_folder.phonegap.plugin.backgroundservice not working for phonegap 3.6.4

### ISSUE THREAD

**Issue by mamata** [Red-Folder/bgs-core#32]
Showing error ---- Uncaught module com.red_folder.phonegap.plugin.backgroundservice.BackgroundService not found", source: file:///android_asset/www/cordova.js .

Please help me.
Thanks in advance

**Comment by Red-Folder** [comment]
Is this specific to 3.6.4 (have you tried over versions?)

I take you have added the plugin as per the instructions?

**Comment by mamata** [comment]
No it is not only specific to that version. Same error is showing for cordova 3.7.0 also .

**Comment by Red-Folder** [comment]
Make sure you have followed the installation instructions properly.

**Comment by NehaAgarwal21** [comment]
Getting same error on phonegap version 3.6.3

**Comment by Red-Folder** [comment]
No meaningful details provided (errors, stack track, etc)  - thus closing
