### ISSUE TITLE
Simple question

### ISSUE THREAD

**Issue by thomaspons** [Red-Folder/bgs-core#36]
I've follow the steps of 'build your own service" and everything works perfectly ! 

I use the runOnce method from javascript and as expected the doWork is called once. 

In my doWork method i initialize a connection to a remote server via an Android client of Socket.IO. 

But i dont understand one thing : when i close the application , the background service is still running but the socket (of socket.io in my background service) is disconnected. 

In fact when the app is closing, the service restart (the runCommand method is called). Is it normal ? Is it an Android specification ?  

If you want more details i can post some piece fo code. 

Really nice job anyway and thx for your time.

**Comment by Red-Folder** [comment]
Sorry for the delay in response.

Sorry, I don't know what Socket.io is.  Is it a separate App?  JavaScript library?

**Comment by thomaspons** [comment]
It's ok sorry for the delay in response. Socket.io was a client android package for manager websockets with a remote server. But everything is working like a charm now :) !
