### ISSUE TITLE
registerforupdatelisner not called after reboot of my phone

### ISSUE THREAD

**Issue by AnandaKarthik** [Red-Folder/bgs-core#37]
Its calling dowork native method only. I need to call javascript function(registerforupdatelisner) in background after reboot of my phone.

**Comment by Red-Folder** [comment]
Apologies for the delay in response.

You are expecting your JavaScript to run when the app isn't running.  This cannot happen as the JavaScript needs the app to be running.  You would need to write code to specifically start the app (after reboot) then re-register the listener.

As a general rule, all doWork() activity should be in Java.  The only work done in JavaScript should be UI updates.

**Comment by AnandaKarthik** [comment]
Okay I understand.

Thanks a lot.
