### ISSUE TITLE
Wrap my sticky service as a cordova plugin

### ISSUE THREAD

**Issue by behrad** [Red-Folder/bgs-core#40]
I want to wrap my android library (packed as an aar) which contains an sticky service (which is currently run even after app is shutdown/terminated in my native client apps) as a cordova plugin.

Can I use this module to achieve what I'm looking for?

I was stuck searching cordova plugin dev docs until I found this! seems promising :+1:

**Comment by Red-Folder** [comment]
If you already have a service, then either:

Convert your service to be based on the Plugin
or
Use code from the Plugin to run your service

The complex piece is in the plugin using AIDL to allow the communication from the plugin to the service.  You are likely to be best using my code as an example and build your own specific plugin - that way you have full control over it.
