### ISSUE TITLE
Listen network connection/disconnection

### ISSUE THREAD

**Issue by thomaspons** [Red-Folder/bgs-core#41]
Is it possible to listen the network state inside the background service ? 

I have to do something when the user lost or retrieve the network connection. 

Any idea on how to do this ? 

Thx for your time

**Comment by Red-Folder** [comment]
There will likely be a broadcast message you can listen for. Android will broadcast messages on a variety of events. You can assign listeners for specific events and perform relevant actions. 

This would need to be native code and you'd have to build a plugin to interface with phonegap.

I don't believe phonegap has a native way of handling. Someone may have already created a polygon

**Comment by thomaspons** [comment]
In pure native it's ok for me ! Thx for your reply
