### ISSUE TITLE
background service close when app swiped away

### ISSUE THREAD

**Issue by abdoljabbar** [Red-Folder/bgs-core#43]
i'm using plugin for running websocket in background service.but when i swipe away app from recent apps my websocket terminate and not working anymore.i notice that when swipe away the app, call background service onDestroy() because of my logcat show:

D/CordovaActivity(23316): CordovaActivity.onDestroy()
D/BackgroundServicePluginLogic(23316): On Destroy Start
D/BackgroundServicePluginLogic(23316): Checking for services
D/BackgroundServicePluginLogic(23316): Found services
D/BackgroundServicePluginLogic(23316): Calling service.close()
D/ServiceDetails(23316): Close called
D/ServiceDetails(23316): Removing ServiceListener
D/BackgroundService(23316): Listener removed
D/ServiceDetails(23316): Removing ServiceConnection
D/ServiceDetails(23316): Close finished
D/BackgroundServicePluginLogic(23316): On Destroy Finish

and cause of this my websocket terminated.so what can i do for this problem?
thank u in advance

**Comment by purplecabbage** [comment]
Swiping away the app actually closes it. This is the expected behavior. 
You will need to look at push notifications if you want to receive messages when the app is closed.

**Comment by abdoljabbar** [comment]
@purplecabbage i used this plugin exactly for this. I said  when i swipe away app from recent apps my websocket that running in background service stopped actually background service stopped.

**Comment by Red-Folder** [comment]
@abdoljabbar Couple of things:

1) Are you testing on Android 4.4?  This seems flakey with background services (see this -> http://stackoverflow.com/questions/20677781/in-android-4-4-swiping-app-out-of-recent-tasks-permanently-kills-application-wi)

2) Are you certain the background service is being stopped?  All the message above are from the plugin (front-end) - none are from the background service itself.  I'd suggest put some additional log.d in the background service to see what is happening to it

3) When you say websockets - how this implemented in the background service?  Is the implementation within Java within the background service or in the front-end app implemented in JavaScript.  If JavaScript, then it definitely wont work as the background service cannot call to JavaScript in a closed application (I ask this, because "websockets" brings JavaScript to my mind).

**Comment by abdoljabbar** [comment]
hi again,
1)No,I'm using android 5.0
2)I swiped away the app 3 time and logcat show this:

D/BackgroundService(10310): onStartCommand run
I/BackgroundService(10310): Initialising the service
I/BackgroundService(10310): Syncing result
D/BackgroundService(10806): onStartCommand run
I/BackgroundService(10806): Initialising the service
I/BackgroundService(10806): Syncing result
D/BackgroundService(11230): onStartCommand run
I/BackgroundService(11230): Initialising the service
I/BackgroundService(11230): Syncing result

3) I run websocket in doWork() of myservice.java

**Comment by abdoljabbar** [comment]
plz help.the problem still going on.

**Comment by Red-Folder** [comment]
@abdoljabbar I am unable to provide assistance at this stage.  I neither have a development environment or a device to test on.  You need to do your own research - you can't expect others to solve your problems.

That said, I believe @purplecabbage is correct in that the swipe will kill background services as well (see http://www.howtogeek.com/169549/what-exactly-happens-when-you-swipe-an-android-app-from-the-recent-apps-list/)

It looks as if the app would need to support onTaskRemoved (http://developer.android.com/reference/android/app/Service.html#onTaskRemoved(android.content.Intent)) to (I assume) restart the background service.

I would suggest you research that.

**Comment by abdoljabbar** [comment]
why do u close the background services in  onDestroy() method? my Problem is there.

**Comment by claudiobadii** [comment]
@abdoljabbar I have your same problem. Did you resolve?

**Comment by abdoljabbar** [comment]
@claudiobadii yes.but a dirty way. i started it again in onTaskRemoved.

**Comment by abhishek-cashify** [comment]
First, I think you should know what exactly happens to running services  when app is swiped away from the recent app list in Android and then make the Android service keep running even after app swipe. I have written a detailed post on this on medium and you may check it .

https://medium.com/@er.abhishek.luthra/effect-of-swiping-an-android-app-in-recent-app-list-1f7984aa4abc

**Comment by Red-Folder** [comment]
@abhishek-cashify Nice little article.  I would however suggest that you refer to the Android guidelines on services.  In most use cases a "constantly running" service is not appropriate and there are better methods to utilise.
