### ISSUE TITLE
Question : Stopping the service

### ISSUE THREAD

**Issue by iamdarren** [Red-Folder/bgs-core#44]
Hi,

ive been testing out this amazing plugin, building on the example provided, and its has been great. But ive been searching for a way to stop the service from MyService.java but unable to do it. Is there anyway that i can stop the service from the java file instead of the front-end javascript ? Thanks !

Cheers,
Darren

**Comment by Red-Folder** [comment]
Try calling this.stopSelf(); from within the doWork()

**Comment by Red-Folder** [comment]
No further activity - assume question is answered
