### ISSUE TITLE
In plugin.xml , "backgroundservice.js" is misspelled.

### ISSUE THREAD

**Issue by ralphpig** [Red-Folder/bgs-core#46]
In 'plugin.xml' : 
\<js-module src="www/backgroundservice.js" name="BackgroundService">
The actual file name is: "www/backgroundService.js"

**Comment by Red-Folder** [comment]
Is this actually causing you a problem?

This hasn't caused problems for me previously (although I've been unable to build an environment for 6 months) - so just wondered if this causing something to fail.

**Comment by ralphpig** [comment]
Yea it was. Specifically 'phonegap run android'. That error was somewhere along the lines of "..... can't find ./www/backgroundservices.js".

I'm not sure if it causes real problems as I haven't actually gotten a service running yet, but it was worth saying.

**Comment by Red-Folder** [comment]
That's odd.  Never seen that before.  But then again it's been a while since I've been able to test the public (see previous comment about dev environment).  Maybe they have made it less forgiving.

I'll get it updated

**Comment by ralphpig** [comment]
Awesome. Maybe that small typo was actually causing you issues.

Thanks.

**Comment by Red-Folder** [comment]
Plugin.xml file is correct
