### ISSUE TITLE
Error when using plugin fo async tasks

### ISSUE THREAD

**Issue by Kujbor** [Red-Folder/bgs-core#47]
Hello,

I am trying to use your plugin to track the user location in back ground service.

I added in doWork() this:

  locationManager = (LocationManager) getSystemService(Context.LOCATION_SERVICE);
  locationManager.requestLocationUpdates(LocationManager.GPS_PROVIDER, 0, 0, this);

I am getting error:

Exception - Can't create handler inside thread that has not called Looper.prepare()

Could u please guide me how to handle this error?

**Comment by Kujbor** [comment]
If someone needs, I do not quite understand what that means, but I wrapped the code inside new Runnable() in BackgroundServicePlugin.java with Looper.prepare (); and Looper.loop (); like this:

                cordova.getThreadPool().execute(new Runnable() {

                    @Override
                    public void run() {

                        Looper.prepare();
                        .......
                        .......
                        Looper.loop();
                    }
                });

And it worked!

**Comment by Red-Folder** [comment]
@Kujbor  - Thanks for updating the question with a response.

I had a similar problem with the looper when I wrote a GPS plugin (a lot of people use the BGS for this).  Apologies for not being able to help at the time.

For reference, I created a Work In Progress GPS plugin - which while not complete - may help if you need further examples.  It can be found here -> https://github.com/Red-Folder/GPS-Service-Plugin

**Comment by veernimbus** [comment]
hey Kujbor, I am trying to do the same thing but i don't the exact code to put inside Looper.prepare() and Looper.loop(). Can you share with me the exact code that you used.
