### ISSUE TITLE
setConfig Method

### ISSUE THREAD

**Issue by yedeveloper** [Red-Folder/bgs-core#50]
I'm having problem with this method, it does not work! I'm trying to send data from javascript to background but does not works. Please help me!  Thank you!

**Comment by Red-Folder** [comment]
Ok, so why is it not working?

Are you getting an error?  If so, post the error

Is it you just don't understand how to use it?  If so, post your code (github or something shareable).  If not prepared to share the entire code, then create a mini-project to demonstrate your problem

**Comment by yedeveloper** [comment]
I don't know if I'm using it wrong. I'm trying to send data, but never get it in background. I'm using the bgs-sample as a guide, but I can't do it. I never receive the data in background.

**Comment by yedeveloper** [comment]
Another problem with the same method. I execute the code from eclipse emulator, it works! perfectly, but I execute the code in a real device and it does not work. I tested in two differents devices and does not work. May you help me? I don't understand why this is happening. Thank you!

**Comment by Red-Folder** [comment]
@yedeveloper Again back to my previous response - I'll need more info.  If your unable to step through via the debugger, then you'll need to right debug steps to a log cat (or a file).  You'll need to provide me with some idea of what is going wrong - generally doing this will help you find your own problem.
