### ISSUE TITLE
How to keeping bgs-core service alive after user exit app

### ISSUE THREAD

**Issue by mongkol38** [Red-Folder/bgs-core#51]
How to keeping bgs-core service alive after user exit app?
I use bgs-core for update badge number (https://github.com/katzer/cordova-plugin-badge) every 3 sec.
I used bgs-core for get number from my jsonp every 3 sec. Every thing run ok if I open my app or minimize my app the badge number can update.
But when I close my app the bgs-core can't get number from my jsonp.
Please help me howto do the bgs-core can get number from my jsonp after close app.

Thank you.

**Comment by Red-Folder** [comment]
Sorry, which part isn't working?

I had a quick look at your code, but couldn't understand what you where executing in the background

**Comment by mongkol38** [comment]
Hello Mark Taylor,

   I am very glad that your email response.
   About my app, my friend make his app using mobile web you can see at
http://www.psschool.in.th ,
   He want to build his app to android application and has more feature Ex,
push notification, badge number and more.
   So, I used cordova to build android application from his mobile web.

   The first version I build app with cordova and add these plugin.
   1. push notification I used this plugin -->
https://github.com/phonegap-build/PushPlugin
   2. and open the web http://www.psschool.in.th I used this plugin -->
https://github.com/apache/cordova-plugin-inappbrowser
   3. I get the app version by this plugin -->
https://github.com/whiteoctober/cordova-plugin-app-version
   4. and alert message using  this plugin -->
https://github.com/apache/cordova-plugin-dialogs
   5. and check the internet connection  using  this plugin -->
https://github.com/apache/cordova-plugin-network-information

   About this app,
   When start app my app will check the internet connection using plugin
cordova-plugin-network-information,
       - if can't connect to internet my app alert message using plugin
cordova-plugin-dialogs
       - if internet connection is connected
              - my app will get app version using plugin
cordova-plugin-app-version
              - my app register PushPlugin
              - my app open http://www.psschool.in.th using plugin
cordova-plugin-inappbrowser
   Everything can work, my app can run success with push notification. and
run on android 4.0+.

   After that he want to show the badge number on the app icon in android (
look like icon on iphone or Line icon when push message come in ). In this
case I use this method to solve problems.,
   1. I used your plugin to build the background process for get the badge
number from server every 3 sec.
   2. Then I used this plugin https://github.com/katzer/cordova-plugin-badge
to show the badge number on the app icon

   Everything can work as well, But when I exit my app I can't get the
badge number from server every 3 sec. but the PushPlugin can work after
exit the app (after exit the app, I send message , my app can push
notification),
   In this case I test by create new simple cordova project with your
sample -->
https://github.com/Red-Folder/bgs-core/wiki/Using-the-MyService-Sample and
add this plugin --> https://github.com/apache/cordova-plugin-dialogs to
beep every 3 sec. Everything ok when i open app or minimize app the beep is
on but when exit app the beep is off.

   Please help or recommend me how to do.
   How to build the background process can get the badge number from server
after exit the app look like PushPlugin. (for simple case the beep is on
every 3 sec. after exit app)
   And I attach my index.html file with this mail.

   I apologize if my English skill is not good.

   Thank you for your advice.

   MONGKOL RODJAN



2016-02-02 3:51 GMT+07:00 Mark Taylor <notifications@github.com>:

**Comment by Red-Folder** [comment]
I believe the problem is that your logic relies on JavaScript to complete the work.  JavaScript is only available to you when the app is running.

Cordova/ Phonegap app is providing a container in which JavaScript (and plugins) can run.  Without it running you cannot use JavaScript (or other plugins).

BGS-Core allows you to extend the BackgroundService class in Java (different from JavaScript).  Putting your functionality into the doWork() method of the class will allow it to run without Cordova/ Phonegap because it is using Java (not JavaScript).  When doing this you are effectively natively programming an Android app.

To reiterate, when the app is closes, the background service has no access to:

* Cordova/ Phonegap functions or plugins
* JavaScript
