### ISSUE TITLE
Build Error duplicate class

### ISSUE THREAD

**Issue by netbitsolutions** [Red-Folder/bgs-core#56]
Hi, i get the following error when i try to complie the Sample project

:compileDebugJavaWithJavacC:\xampp\htdocs\gap_projects\beekn2\platforms\android\
src\com\red_folder\phonegap\plugin\backgroundservice\MyService.java:13: error: d
uplicate class: com.red_folder.phonegap.plugin.backgroundservice.sample.MyServic
e
public class MyService extends BackgroundService {
       ^
1 error
 FAILED

**Comment by Red-Folder** [comment]
Has the plugin been installed twice somehow?

I don't remember seeing a similar problem to this previously so I'd suspect it is a problem with how the plugin has been installed.

Clean it all back and install again seem the best advice

**Comment by Red-Folder** [comment]
Closed ... no response
