### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by netbitsolutions** [Red-Folder/bgs-core#58]
Step 3 on how to build a background  [https://github.com/Red-Folder/bgs-core/wiki/Build-your-own-Background-Service] service generates the following errors

:processDebugResourcesC:\xampp\htdocs\gap_projects\beekn\platforms\android\res
ml\config.xml:20 : AAPT: Error parsing XML: unbound prefix
 FAILED

FAILURE: Build failed with an exception.

BUILD FAILED

Total time: 5.944 secs

* What went wrong:
Execution failed for task ':processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal
xecException: Process 'command 'C:\Users\Admin\Documents\Transfer\DRIVE C\MISC
ppsdk\sdk\build-tools\23.0.2\aapt.exe'' finished with non-zero exit value 1

**Comment by Red-Folder** [comment]
What is on line 20 of config.xml?

Reads like the XML isn't properly formed maybe

**Comment by netbitsolutions** [comment]
Hi, thanks . My bad, i  thought  cordova will over write the start service tag meant for the Androidmanifes.xml, but i was wrong. I simply pasted the code in it works fine

 <service android:name="com.red_folder.phonegap.plugin.backgroundservice.geo.GeoService">
            <intent-filter>
                <action android:name="com.red_folder.phonegap.plugin.backgroundservice.geo.GeoService" />
            </intent-filter>
        </service>
