### ISSUE TITLE
Plugin unable to bind to background service

### ISSUE THREAD

**Issue by JugnuPathak** [Red-Folder/bgs-core#61]
I'm try to use this for appgyver steroids but when I call startService then it return an error **"Plugin unable to bind to background service"**. other methods are work perfectly.

**Comment by Red-Folder** [comment]
No idea what appgyer steroids is ... doesn't sound legal ;)

Check manifest that the service is registered correctly.  Check names are all correct, etc

All else fails, create a clean project and install bgs-sample and start from there

**Comment by Red-Folder** [comment]
Closed ... no response
