### ISSUE TITLE
Implement a geolocation using cordova

### ISSUE THREAD

**Issue by Jorgee97** [Red-Folder/bgs-core#69]
Well, I have been trying to implement this achievement, I have tested a lot of plugins until i found this one, my issue comes when i try to implement the service, I don't know what am doing wrong but I always get the message that my services is not started and I there is a error, so in the order of things I'm using your plugin + socket.io java client + LocationListener, but anything is working, could you give me a list to do for complete my achievement, I'm stuck.

**Comment by Red-Folder** [comment]
Sorry to come to this so late ... are you still having problems?

**Comment by Jorgee97** [comment]
I already implement something, but is kind of unestable, I mean that sometimes it work like a charm and sucessfull send the data to my server through socket.io, but when the user close the app sometimes it takes to long for start the service.

**Comment by Red-Folder** [comment]
What is the problem you are experiencing?

I take it you are trying to push the devices location to a server on a regular basis?

If it helps, I produced a draft plugin to do this (https://github.com/Red-Folder/GPS-Service-Plugin).  It isn't complete, but may provide some assistance to you

**Comment by kpwa** [comment]
any assistance how i can grab device location from background service and send back to my webview running app?

**Comment by Red-Folder** [comment]
@kpwa Do a search of Android Geo-Location - there are a lot of examples out there.  The draft plugin I mention above should provide some assitance
