### ISSUE TITLE
Installing the plugin 

### ISSUE THREAD

**Issue by shockX92** [Red-Folder/bgs-core#72]
I am developing a cross platform application and I have some problem with updating this plugin Cordova-Plugin-BackgroundService

I saw you said there is another plugin more recent : https:// github.com/Red-Folder/bgs-core . But when I install it I have some problem 
![capture](https://cloud.githubusercontent.com/assets/25366608/22332729/abddd52a-e3d2-11e6-9cb5-052867eea4f6.PNG)

Do you have any idea how to solve this ? Do I have to update something else ?

Is there any alternative ?

thanks by advance !

**Comment by Red-Folder** [comment]
Not see the error before.  But if you do a search on "unsupportedclassversionerror 52.0" you get plenty of results - such as http://stackoverflow.com/questions/22489398/unsupported-major-minor-version-52-0

It looks to be a mismatch in your compiled code and your runtime.

I don't believe this has anything to do with the plugin itself.

**Comment by Red-Folder** [comment]
In addition, picking up on your "I am developing a cross platform application" comment;

Please note that the plugin is Android only

**Comment by shockX92** [comment]
Thank you for your responde.
It was just to introduce the subject. 
I will search in that direction, thank you for your time :)

**Comment by shockX92** [comment]
![image](https://cloud.githubusercontent.com/assets/25366608/22421219/6cdbca28-e6e6-11e6-99d9-20ddc4a98e16.png)
Sorry to bother you again but I have another error. I have search for similar problem but they are all related with something called maven and I have no idea what it is ...

**Comment by Red-Folder** [comment]
Maven is a build tool -> https://maven.apache.org/

Basically think of it as something you provide instructions on how to build the Android app, and it does the job.

To equate to house building;

* You are the architect - you define the how the house should look along with materials to be used and how they should be composed
* Maven is the builder who follows you instructions
* App is the House

Gradle (also mention above) is also a build tool -> https://gradle.org/

Try having a look at this to see if it helps: https://developer.android.com/studio/releases/gradle-plugin.html

**Comment by Red-Folder** [comment]
I'd also recommend trying to build the "original" version of the application as it was provided to you (assuming you haven't)

It looks like you are getting a lot build problems which will likely be related to your development environment - not Android, Cordova or the plugin.

Basically try to narrow down the variables.  Make sure that you can build the getting started for Android (https://developer.android.com/about/start.html) & Cordova (https://cordova.apache.org/docs/en/2.5.0/guide/getting-started/android/)

**Comment by shockX92** [comment]
Thanks for all your help :)
