### ISSUE TITLE
[resolved] Plugin can't be installed

### ISSUE THREAD

**Issue by iwantwin** [Red-Folder/bgs-core#86]
Was receiving the following error:

```
Error: Failed to fetch plugin https://github.com/Red-Folder/bgs-core via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module
```

Any clue what the problem is here? It was working just 3 weeks ago! And I really need this to work :#

**Comment by iwantwin** [comment]
Oh actually, answering my own question:

Using the option --nofetch (cordova@7.0.1) fixed it:
`cordova plugin add ../my-plugin --nofetch`

Apparently they changed the way they fetch plugins in cordova 7.x, and --nofetch uses the old way of fetching :)

Feel free to close!

**Comment by Red-Folder** [comment]
Thanks for the feedback
