### ISSUE TITLE
running cordova inside of a service

### ISSUE THREAD

**Issue by andrewvmail** [Red-Folder/bgs-core#89]
has anyone have any success running a headless browser inside a service with cordova plugins wired in. i was able to get the browser part running but cant seem to figure out how to initialize the plugins inside or a service

Cheers
AT

**Comment by Red-Folder** [comment]
So you want to run a headless browser from within the service execution context?

**Comment by andrewvmail** [comment]
Yeah I got the headless browser part working with [XWalkInitializer](https://crosswalk-project.org/apis/embeddingapidocs_v7/org/xwalk/core/XWalkInitializer.html), but having a hard time with getting cordova running in it. I actually found someone figured it out with the regular WebView [here](https://github.com/cozy/cordova-jsbackgroundservice/issues/3) and it works but on my project I have to use crosswalk. I guess the issue is the [XWalkWebViewEngine](https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview/blob/master/platforms/android/src/org/crosswalk/engine/XWalkWebViewEngine.java) is more sensitive than the [SystemWebViewEngine](https://github.com/apache/cordova-android/blob/master/framework/src/org/apache/cordova/engine/SystemWebViewEngine.java) so the hack doesn't work

Long story short I don't need to this anymore because I found what I want to do [with this](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#application-force-closed) 

But out of curiosity, wondering if anyone else ever got cordova inside a service. The way I imagine it is you write a service in JS and have 2 independent JS runtime. Not sure maybe this is architecturally and fundamentally a bad idea thats why its so hard to get this working ... 

While writing just stumbled on to this [android-cheats-and-tips-invisible-activity](http://androidblog.reindustries.com/android-cheats-and-tips-invisible-activity/) I'm new to native android but I guess this might work too.

Just for closure I probably will play around some more to test out that idea. 

tagging this other [issue](https://github.com/Red-Folder/bgs-core/issues/17) I think the guy might find this interesting, since im working on a similar app

Cheers

**Comment by Red-Folder** [comment]
What are you actually trying to achieve (functional outcome rather than technical solution)?

It feels as if the architecture is very complex.

**Comment by andrewvmail** [comment]
Wake up the app on a silent push message then either download some messages or connect an incoming call. should work when app is killed or when app is in background after all that should disconnect and cleanup after it self.

I guess your right it does feels kinda complex

**Comment by Red-Folder** [comment]
I'd advise you have a look at push messaging (Google Cloud Messaging).

If you see https://developers.google.com/cloud-messaging/, the description for Downstream Messaging:

`... kicking off background processing...`

I've not used myself so could comment on how easy it would be to use - but there is a lot of "noise" about this sort of technology - so I'd expect a lot of samples floating around.  Good luck
