### ISSUE TITLE
onStartCommand implementation 

### ISSUE THREAD

**Issue by mikedumont** [Red-Folder/bgs-core#9]
Hello, 

First of all thnx for the plugin, it works great, i don't really have a problem but i would like to share something with you and ask your opinion about my solution.

In my previous post on this repo i had a problem with the doWork method, it didn't run when i used  onStartCommand in my backgroundservice. While I thought i solved the problem by reinstalling the plugin, it was only partly the sollution. I noticed yesterday that my backgroundservice started onboot as supposed to. But the timer didn´t start running.. Again the dowork and all the other methods didn´t get triggerd because of the onStartCommand...

So i started to digg around in the plugin and i noticed you used:
	
       public void onStart(Intent intent, int startId) {
		initialiseService();
	}

If i'm correct this method is deprecated, so can't you replace this with the onStartCommand? Or use it next to the onStart method?

Because I think this is what causing my problem:
I use onStartCommand in my bachgroundservice, I need to use the annotation Overridde. In the plugin their isn't an onStartcommand (only onStart) so the initialiseService method does'nt get triggerd. Because the onStartCommand doesn't override onStart (<--guessing here).

I tested and solved this by using an onStartcommand in the plugins BackGroundService.java like this:
        
      @Override
            public int onStartCommand(Intent intent, int flags, int startId) {
                initialiseService();
            return START_REDELIVER_INTENT;   //Could also be START_STICKY
        }

and this piece of code in my backgroundservice:

    @Override
    public int onStartCommand(Intent intent, int flags, int startId) {
        super.onStartCommand(intent, flags, startId);
        handleOnStart(intent);
         Log.d("ONSTARTCOMMAND", "intent" + intent);
        return START_REDELIVER_INTENT;  
    }

After doing this everything runs like a charm. What are your ideas on this subject?
(i'm not even close to be a JAVA pro so correct me if i'm wrong) 

Greetings Mike

**Comment by Red-Folder** [comment]
Notes from review of http://developer.android.com/reference/android/app/Service.html#onStart(android.content.Intent,int)

* onStartCommand called after onCreate (I assume also after onStart)
* onStartCommand should return START_STICKY
* onStartCommand can be called multiple times
* stopService or stopSelf will only be called once
* All cleanup (stopping threads, unregistering receivers) should be complete upon returning from onDestroy().
* Confirmed that the spec says "This method was deprecated in API level 5. Implement onStartCommand(Intent, int, int) instead."
* Note that service will run on the same thread as the UI.  Need to move all the processing onto seperate thread (assuming I'm not already doing)

**Comment by Red-Folder** [comment]
Tasks to do:

1) Migrate current onStart to onStartCommand - returning the START_STICKY
2) Check that all clean up activity will be performed
3) Run the doWork() in a separate thread (assuming I'm not already)

**Comment by Red-Folder** [comment]
Committed 1 & 2 above in commit e2eee2495f0e50b9968d7dc144559ffde69fb788

**Comment by Red-Folder** [comment]
Double checked that the doWork() in running in a separate (which it is).  Runs as a separate TimerTask.

This issue considered closed (please log fresh issue if not working correctly)
