### ISSUE TITLE
What is service will not running when app closed ?

### ISSUE THREAD

**Issue by RizkaOMG** [Red-Folder/bgs-core#90]
I try your plugin and it work and service running perfectly but when i try clear chace in android phone service come close to. I just want ask, is it possible MyService.java always run when user clear chace on android phone ? Because I try and follow your this [[Using the MyService Sample]](https://github.com/Red-Folder/bgs-core/wiki/Using-the-MyService-Sample) example, Service running but when clear chace app service not work.
Thanks

**Comment by Red-Folder** [comment]
What is "clear chace"?

**Comment by RizkaOMG** [comment]
it closed running applications

**Comment by Red-Folder** [comment]
So user starts App (visible on screen), background logic running ok?

User closes App (switches to another app for example), background logic stops working?

Is this what you are describing?

**Comment by RizkaOMG** [comment]
I mean, if i have more then 1 app has running and i stop it with clear default menu on android

**Comment by Red-Folder** [comment]
Sorry, I don't know what you mean by "clear default menu"

**Comment by RizkaOMG** [comment]
Sorry for the bad explanation,
I mean, if i have more than have more than 3 app runing at the same time, it will used use a lot of RAM and android mobile have some function to closed all running apps. That function I called clear chace.

**Comment by Red-Folder** [comment]
Is it the "Clear All" mention in step 3 on this article -> https://www.tomsguide.com/us/close-android-apps,news-21281.html

If so, have a read of this (https://stackoverflow.com/questions/36324794/android-system-killed-my-service-when-i-clear-all-recent-app) - see if anything helps.

**Comment by RizkaOMG** [comment]
Thanks for share some article that's very helpful
