### ISSUE TITLE
It's Possible MyService.java Call Javascript Function ?

### ISSUE THREAD

**Issue by RizkaOMG** [Red-Folder/bgs-core#91]
I try make MyService.java run some function from javascript because when user clear all recent app function on app will be stop but MyService.java stiil running. It's possible to call JS function in MyService.java ? because I need notification when APP closed. I used local notification from cordova. I already used javax.script but it show error when I build android.
Thanks

**Comment by Red-Folder** [comment]
No, there is no method to run JavaScript from MyService.java if the Cordova instance has been killed.

I would advise moving converting your logic from JavaScript to Jave and running within MyService.java

If however, you are just pushing notifications to your app - I'd suggest looking at something like [Google Cloud Messaging](https://developers.google.com/cloud-messaging/) instead

**Comment by iamisti** [comment]
@Red-Folder do you think it is possible to call a third party android library from 'MyService'? Can you put me on the track and tell me how if it's possible? Thanks a lot in advance!

**Comment by iamisti** [comment]
wow that was a nice answer :D
